# Generated by Django 4.2.7 on 2024-01-31 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_customuser_managers_customuser_email_otp_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
    ]
